routes/dashboard.php
<?php

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('a/{personnel_no}/', 'Auth\LoginController@programaticallyEmployeeLogin')->name('login.a');
    

Route::get('/config-cache', function() {
    Artisan::call('config:cache');
    return "Cache is cleared";
});
Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});
Route::get('/', function () {
    if (!Auth::user()) {
        // untuk virutal host
        // return redirect()->route('login');
        return redirect()->away('https://sso.krakatausteel.com');

        // jika tidak menggukalan virtual host
        // return redirect()->guest('/public/login');
    } else {
        
        return redirect()->route('dashboard');
    }
});



Route::group(['middleware' => ['auth','role:administrator']], function () {
    Route::resource('user', 'UserController')->parameters(['user' => 'id']);
});

Route::group(['middleware' => ['auth','role:administrator|admin']], function () {
    Route::resource('materi', 'MateriRakoorController')->parameters(['materi' => 'id']);
    
    Route::get('partisipan/user', 'PartisipanController@user')->name('partisipan.user');
    Route::get('ambil_unit/performance', 'UnitController@ambil_unit');
    Route::resource('partisipan', 'PartisipanController')->parameters(['partisipan' => 'id']);
    
    Route::get('notulis/user', 'NotulisController@user')->name('notulis.user');
    Route::resource('notulis', 'NotulisController')->parameters(['notulis' => 'id']);
});

Route::group(['middleware' => ['auth','role:notulis|administrator|admin']], function () {
    Route::get('notulen/user/{q?}', 'NotulenController@user')->name('notulen.user');
    Route::resource('notulen', 'NotulenController')->parameters(['notulen' => 'id']);
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/unit', 'UnitController');

    // master kpi
    // Route::resource('/kpi', 'KpiController');
    Route::get('/dashboard/{kode?}/{nama?}/{tahun?}/{bulan?}', 'HomeController@index');
    Route::get('/kpi', 'KpiController@index')
        ->name('kpi.index');
    Route::get('import/kpi', 'KpiController@formImport')
        ->name('kpi.import');
    Route::get('kpi/{id}', 'KpiController@edit')
        ->name('kpi.edit');
    Route::put('kpi/{id}', 'KpiController@update')
        ->name('kpi.update');
    Route::post('/import/kpi/process','KpiController@importProcess')
        ->name('kpi.import.process');

    // master unit
    Route::resource('/unit', 'UnitController');
    Route::get('pic/unit/{id}', 'UnitController@formImport');
    Route::post('pic/unit/process', 'UnitController@importProcess')
        ->name('unit.pic.process');

    // deployment
    // Route::resource('/deployment', 'DeploymentController');
    Route::get('/deployment', 'DeploymentController@index')
        ->name('deployment.index');
    Route::get('import/deployment', 'DeploymentController@formImport')
        ->name('deployment.import');
    Route::get('/deployment/edit/{id}', 'DeploymentController@edit');
    Route::get('/deployment/delete/{id}', 'DeploymentController@remove');
    Route::post('/deployment/update/', 'DeploymentController@update');
    Route::get('/deployment/carikodeunit/', 'DeploymentController@carikodeunit');
    Route::post('import/deployment/process', 'DeploymentController@importProcess')
        ->name('deployment.import.process');

    // deployment target
    Route::get('target/deployment', 'DeploymentTransactionController@index')
        ->name('deployment.target.index');
    Route::get('target/{id}/deployments', 'DeploymentTransactionController@create')
        ->name('deployment.target.create');
	Route::get('validasitarget/{id}/deployments', 'DeploymentTransactionController@validasitarget')
        ->name('deployment.target.validasitarget');
    Route::post('target/deployment','DeploymentTransactionController@store')
        ->name('deployment.store');
    Route::get('target/deployment/{id}/show','DeploymentTransactionController@show')
        ->name('deployment.target.show');
    Route::get('target/deployment/{id}/validasi/admin','DeploymentTransactionController@formValidasiAdmin')
        ->name('deployment.target.formvalidasiadmin');
    Route::get('deployments/unvalid/{id}','DeploymentTransactionController@Unvalidasi');
    Route::put('target/deployment/{id}/validasi/admin','DeploymentTransactionController@update')
        ->name('deployment.target.validasiadmin');
    Route::get('target/deployment/{id}/validasi/atasan','DeploymentTransactionController@formValidasiAtasan')
        ->name('deployment.target.formvalidasiatasan');
    Route::get('target/deployment/allvalidasitarget','DeploymentTransactionController@allvalidasitarget');
    Route::get('target/deployment/onevalidasitarget','DeploymentTransactionController@onevalidasitarget');
    Route::put('target/deployment/{id}/validasi/atasan','DeploymentTransactionController@validasiAtasan')
        ->name('deployment.target.validasiatasan');

    // deployment realization
    Route::get('realisasi/deployment','DeploymentRealizationController@index')
        ->name('deployment.realisasi.index');  
    Route::get('realisasi/hapusfile/','DeploymentRealizationController@hapusfile');
    Route::get('realisasi/deployment/{id}/show','DeploymentRealizationController@show')
        ->name('deployment.realisasi.show');  
	Route::post('realisasi/deployment','DeploymentRealizationController@store')
        ->name('deployment.realisasi.store');
	Route::post('realisasi/insrealisasi','DeploymentRealizationController@insrealisasi');
	Route::post('realisasi/insalasannya','DeploymentRealizationController@insalasan');
    Route::get('realisasi/validasi','DeploymentRealizationController@validasirealisasi');
    Route::get('realisasi/kembalikan','DeploymentRealizationController@kembalikanrealisasi');
    Route::get('realisasi/deployment/{id}/validasi','DeploymentRealizationController@formValidasi')
        ->name('deployment.realisasi.formvalidasi');
    Route::put('realisasi/deployment/{id}/validasi','DeploymentRealizationController@processValidasi')
        ->name('deployment.realisasi.validasi');
    Route::get('realisasi/validasiperbulan','DeploymentRealizationController@validasiperbulan');
     // deployment capaian
     Route::get('capaian/deployment','CapaianController@index')
     ->name('deployment.capaian.index');  
     Route::get('capaian/deployment/atasan','CapaianController@indexatasan');
     Route::get('capaian/deployment/laporancapaian','CapaianController@laporancapaian');
     Route::get('capaian/deployment/laporancapaianadmin/{kode?}/{nama?}/{tahun?}','CapaianController@laporancapaianadmin');
     Route::get('capaian/deployment/laporan/{kode?}/{tahun?}','CapaianController@laporan');
     Route::get('capaian/deployment/validasi/{kode?}/{tahun?}','CapaianController@laporan_validasi');
     Route::get('capaian/deployment/view_laporan/{kode?}/{tahun?}','CapaianController@view_laporan');
     Route::get('capaian/deployment/view_laporan_acc/{kode?}/{tahun?}','CapaianController@view_laporan_acc');
     
});


Route::get('/debug', 'DebugController@index');
Auth::routes();

resources/views/core-ui/layouts/_footer.blade.php
<footer class="app-footer">
    <div>
        <a href="https://coreui.io">PT KRAKATAU STEEL</a>
        <span>&copy; 2019 Teams web</span>
    </div>
    <div class="ml-auto">
        <span>Powered by</span>
        <a href="https://coreui.io">CoreUI</a>
    </div>
</footer>

resources/views/core-ui/layouts/_layout.blade.php
@push('navbar')
    @include('core-ui.layouts._navbar')
@endpush
@push('menukiri')
    @include('core-ui.layouts._menukiri')
@endpush
@push('menukanan')
    @include('core-ui.layouts._menukanan')
@endpush
@push('footer')
    @include('core-ui.layouts._footer')
@endpush

resources/views/core-ui/layouts/_menukanan.blade.php
<aside class="aside-menu">
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#timeline" role="tab">
                <i class="icon-list"></i>
            </a>
        </li>
    </ul>
    <!-- Tab panes-->
    <div class="tab-content">
        <div class="tab-pane active" id="timeline" role="tabpanel">
            <div class="list-group list-group-accent">
                <div class="list-group-item list-group-item-accent-secondary bg-light text-center font-weight-bold text-muted text-uppercase small">Today</div>
                <div class="list-group-item list-group-item-accent-warning list-group-item-divider">
                    
                </div>
            </div>
        </div>
    </div>
</aside>

resources/views/core-ui/layouts/_menukiri.blade.php
<div class="sidebar">
    <div style="border-radius:10px;text-transform:uppercase;background:#c4c5d0;width:90%;padding:5px;height:150px;margin:10px;text-align:center;color:#000">
        <img src="{{url('img/logoo.png')}}" width="90%"><h6><u>{{substr(Auth::user()->name,0,20)}}</u><br>{{Auth::user()->username}}</h6>
    </div>
    <nav class="sidebar-nav">
        <ul class="nav">
            @if(Auth::user()->hasRole('boss') || Auth::user()->hasRole('administrator'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ url('dashboard') }}">
                        <i class="nav-icon icon-speedometer"></i> Dashboard
                    </a>
                </li>
            @else
                <li class="nav-item">
                    <a class="nav-link" href="{{ url('dashboard?kodenyaunit=') }}">
                        <i class="nav-icon icon-speedometer"></i> Dashboard
                    </a>
                </li>
            @endif

            <li class="nav-title">Menu</li>

            @role('administrator')
            <li class="nav-item">
                <a class="nav-link" href="{{ route('unit.index') }}">
                    <i class="nav-icon icon-people"></i> User</a>
            </li>
            @endrole
            
            @role('administrator')
                <li class="nav-item nav-dropdown ">
                    <a class="nav-link nav-dropdown-toggle" href="#">
                        <i class="nav-icon icon-list"></i> Master Data</a>
                    <ul class="nav-dropdown-items" style="margin-left:10px">
                        <li class="nav-item">
                            <a href="{{ route('kpi.index') }}" class="nav-link" href="base/breadcrumb.html">
                            <i class="nav-icon icon-minus"></i> Kpi </a>
                        </li>
                        {{-- <li class="nav-item">
                            <a href="{{ route('unit.index') }}" class="nav-link" href="base/breadcrumb.html">
                            <i class="nav-icon icon-circle"></i> Unit </a>
                        </li> --}}
                        <li class="nav-item">
                            <a href="{{ route('deployment.index') }}" class="nav-link" href="base/breadcrumb.html">
                            <i class="nav-icon icon-minus"></i> Deployment </a>
                        </li>
                    </ul>
                </li>
            @endrole
            <li class="nav-item nav-dropdown ">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-list"></i>Transaksi</a>
                <ul class="nav-dropdown-items" style="margin-left:10px">
                    <li class="nav-item">
                        <a href="{{ route('deployment.target.index') }}" class="nav-link" href="base/breadcrumb.html">
                        <i class="nav-icon icon-minus"></i> Target bulanan </a>
                    </li>
                    @role('boss')
                        <li class="nav-item">
                            <a href="{{ url('/capaian/deployment/validasi') }}" class="nav-link" href="base/breadcrumb.html">
                            <i class="nav-icon icon-minus"></i> Realisasi per bulan </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url('capaian/deployment/laporan/') }}" class="nav-link" href="base/breadcrumb.html">
                            <i class="nav-icon icon-minus"></i>Laporan Capaian </a>
                        </li>

                    @endrole

                    @role('keyperson|adminkpi')
                        <li class="nav-item">
                            <a href="{{ route('deployment.realisasi.index') }}" class="nav-link" href="base/breadcrumb.html">
                            <i class="nav-icon icon-minus"></i> Realisasi per bulan </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url('capaian/deployment/laporan/') }}" class="nav-link" href="base/breadcrumb.html">
                            <i class="nav-icon icon-minus"></i>Laporan Capaian </a>
                        </li>
                    @endrole

                    @role('administrator')
                        <li class="nav-item">
                            <a href="{{ route('deployment.realisasi.index') }}" class="nav-link" href="base/breadcrumb.html">
                            <i class="nav-icon icon-minus"></i> Realisasi per bulan </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url('capaian/deployment/laporan/') }}" class="nav-link" href="base/breadcrumb.html">
                            <i class="nav-icon icon-minus"></i>Laporan Capaian </a>
                        </li>
                    @endrole
                    
                </ul>
            </li>
            {{-- <li class="nav-item">
                <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="nav-icon fa fa-sign-out"></i> Logout </a>
                
            </a> --}}
            </li>
        </ul>
    </nav>

    {{-- <button class="sidebar-minimizer brand-minimizer" type="button"></button> --}}
</div>

resources/views/core-ui/layouts/_navbar.blade.php
<header class="app-header navbar mb-0">
    <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">
        <img class="navbar-brand-full" src="img/krakatausteel-logo-text.png"  height="35" alt="CoreUI Logo">
        <img class="navbar-brand-minimized" src="img/krakatausteel-logo.png" width="30" height="30" alt="CoreUI Logo">
    </a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="col d-md-down-none">
        {{-- <h3 class="text-uppercase">{{ config('app.name') }}</h3> --}}
        <h3 class="text-uppercase">Performance Management System</h3>
    </div>
    
    {{-- <ul class="nav navbar-nav d-md-down-none">
        <li class="nav-item px-3">
            <a class="nav-link" href="#">Dashboard</a>
        </li>
        <li class="nav-item px-3">
            <a class="nav-link" href="#">Users</a>
        </li>
        <li class="nav-item px-3">
            <a class="nav-link" href="#">Settings</a>
        </li>
    </ul> --}}


    <ul class="nav navbar-nav d-md-down-none">
       
            <li class="nav-item px-3">
                <a download href="{{ url('/storage/images/001.pdf') }}"  data-toggle="tooltip" data-placement="bottom" title="Panduan penggunaan aplikasi">
                    {{-- <i class="ace-icon fa fa-question-circle fa-2x"></i> --}}
                    <i><img src="{{ url('/storage/images/01.png') }}" style="width:50;height:50px;">Buku Panduan</i>
                </a>
            </li>
             <li class="nav-item px-3">                
                <a href="{{ route('logout') }}"
                    onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                    <i class="fa fa-lock"></i>
                    {{ __('Logout') }}&nbsp;&nbsp;
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            
        </li>
    </ul>


    {{-- <ul class="nav navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <object data="https://portal.krakatausteel.com/eos/storage/pic/{{ Auth::user()->id }}.jpg" class="rounded" type="image/png" width="25px">
                    <img class="img-avatar" src="img/avatars/7.jpg" alt="Stack Overflow logo and icons and such">
                </object>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-header text-center text-uppercase">
                    <strong>{{ Auth::user()->name }}</strong>
                </div>
                <object data="https://portal.krakatausteel.com/eos/storage/pic/{{ Auth::user()->id }}.jpg" class="mx-auto d-block img-thumbnail my-2" type="image/png" width="100px">
                    <img class="rounded" src="img/avatars/7.jpg" alt="-" width="100%">
                </object>
                
                <a class="dropdown-item" href="{{ route('logout') }}"
                    onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                    <i class="fa fa-lock"></i>
                    {{ __('Logout') }}
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul> --}}

    {{-- <button class="navbar-toggler aside-menu-toggler d-md-down-none" type="button" data-toggle="aside-menu-lg-show">
        <span class="navbar-toggler-icon"></span>
    </button>
    <button class="navbar-toggler aside-menu-toggler d-lg-none" type="button" data-toggle="aside-menu-show">
        <span class="navbar-toggler-icon"></span>
    </button> --}}
</header>

resources/views/core-ui/layouts/app.blade.php
<!DOCTYPE html>
<!--
* CoreUI - Free Bootstrap Admin Template
* @version v2.1.11
* @link https://coreui.io
* Copyright (c) 2018 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://coreui.io/license)

*
* PT KRAKATAU INFORMATION TECHNOLOGY
* kUROB
* JCP@2019
*
-->

<html lang="en">

<head>
    <base href="{{ asset('./') }}">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
    <meta name="author" content="Łukasz Holeczek">
    <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
    <title>{{ config('app.name') }}</title>
    <link rel="icon" href="{{ asset('img/krakatausteel-logo.png') }}">

    <!-- Icons-->
    <link href="{{ asset('vendors/@coreui/icons/css/coreui-icons.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendors/flag-icon-css/css/flag-icon.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendors/simple-line-icons/css/simple-line-icons.css') }}" rel="stylesheet">
    <style>
        .select2 {
            width:100%!important;
        }
    </style>
    @stack('style')

    <!-- Main styles for this application-->
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('vendors/pace-progress/css/pace.min.css') }}" rel="stylesheet">
    <style>
        #loading {
                    position: fixed;
                    left: 0px;
                    top: 0px;
                    width: 100%;
                    height: 100%;
                    z-index: 9999;
                    background: url({{url('img/loading.gif')}}) 50% 50% no-repeat #fff;
                }
            .skin-blue .sidebar-menu>li:hover>a, .skin-blue .sidebar-menu>li.active>a, .skin-blue .sidebar-menu>li.menu-open>a {
            color: #000;
            background: #5d4747;
            }
            .thth{padding:3px;border:solid 1px #fff6f6;background:#efeff9;font-size: 11px;}
            .tdtd{padding-left:3px;padding-right:3px;border:solid 1px #fff6f6;font-size: 11px;font-family: sans-serif;background:#fff;}
            .pesan{font-style:italic;color: #131354;font-size: 12px;font-family: sans-serif;}
    </style>
    <script src="{{url('js/jquery-1.11.1.min.js')}}"></script>
    <script type="text/javascript">
            $(window).load(function() { $("#loading").fadeOut(500); })
    </script>
    <script>
        window.dataLayer = window.dataLayer || [];

        // function gtag() {
        //     dataLayer.push(arguments);
        // }
        // gtag('js', new Date());
        // // Shared ID
        // gtag('config', 'UA-118965717-3');
        // // Bootstrap ID
        // gtag('config', 'UA-118965717-5');
    </script>
</head>
@stack('login')
<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
    <div id="loading"></div>
    {{-- navigasi bar --}}
    @stack('navbar')
    {{-- navigasi bar --}}

    <div class="app-body">
        {{-- MENU SEBELAH KIRI --}}
        @stack('menukiri')
        {{-- AKHIR MENU SEBELAH KIRI --}}

        {{-- KONTEN --}}
        <main class="main">
            @yield('content')
        </main>
        {{-- AKHIR KONTEN --}}

        {{-- MENU SEBELAH KANAN --}}
        @stack('menukanan')
        {{-- AKHIR MENU SEBELAH KANAN --}}
    </div>
    
    @stack('footer')
    <!-- CoreUI and necessary plugins-->
    <script src="{{ asset('vendors/jquery/js/jquery.min.js') }}"></script>
    @stack('plug')
    <script type="text/javascript" src="{{url('js/jquery-1.11.1.min.js')}}"></script>  
    <script type="text/javascript" src="{{url('js/jquery.canvasjs.min.js')}}"></script>

    
    <script src="{{ asset('vendors/popper.js/js/popper.min.js') }}"></script>
    <script src="{{ asset('vendors/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('vendors/pace-progress/js/pace.min.js') }}"></script>
    <script src="{{ asset('vendors/perfect-scrollbar/js/perfect-scrollbar.min.js') }}"></script>
    <script src="{{ asset('vendors/@coreui/coreui/js/coreui.min.js') }}"></script>
    <!-- Plugins and scripts required by this view-->
    <!-- script dari view -->
    @stack('load')
    <script>
    
        function url() {
            var baseUrl = "{{ url('') }}/";
            return baseUrl;
        }
    </script>
    @stack('script')
    <!-- script dari view -->
</body>

</html>