routes/dashboard.php
<?php

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('a/{personnel_no}/', 'Auth\LoginController@programaticallyEmployeeLogin')->name('login.a');
    

Route::get('/config-cache', function() {
    Artisan::call('config:cache');
    return "Cache is cleared";
});
Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});
Route::get('/', function () {
    if (!Auth::user()) {
        // untuk virutal host
        // return redirect()->route('login');
        return redirect()->away('https://sso.krakatausteel.com');

        // jika tidak menggukalan virtual host
        // return redirect()->guest('/public/login');
    } else {
        
        return redirect()->route('dashboard');
    }
});



Route::group(['middleware' => ['auth','role:administrator']], function () {
    Route::resource('user', 'UserController')->parameters(['user' => 'id']);
});

Route::group(['middleware' => ['auth','role:administrator|admin']], function () {
    Route::resource('materi', 'MateriRakoorController')->parameters(['materi' => 'id']);
    
    Route::get('partisipan/user', 'PartisipanController@user')->name('partisipan.user');
    Route::get('ambil_unit/performance', 'UnitController@ambil_unit');
    Route::resource('partisipan', 'PartisipanController')->parameters(['partisipan' => 'id']);
    
    Route::get('notulis/user', 'NotulisController@user')->name('notulis.user');
    Route::resource('notulis', 'NotulisController')->parameters(['notulis' => 'id']);
});

Route::group(['middleware' => ['auth','role:notulis|administrator|admin']], function () {
    Route::get('notulen/user/{q?}', 'NotulenController@user')->name('notulen.user');
    Route::resource('notulen', 'NotulenController')->parameters(['notulen' => 'id']);
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/unit', 'UnitController');

    // master kpi
    // Route::resource('/kpi', 'KpiController');
    Route::get('/dashboard/{kode?}/{nama?}/{tahun?}/{bulan?}', 'HomeController@index');
    Route::get('/kpi', 'KpiController@index')
        ->name('kpi.index');
    Route::get('import/kpi', 'KpiController@formImport')
        ->name('kpi.import');
    Route::get('kpi/{id}', 'KpiController@edit')
        ->name('kpi.edit');
    Route::put('kpi/{id}', 'KpiController@update')
        ->name('kpi.update');
    Route::post('/import/kpi/process','KpiController@importProcess')
        ->name('kpi.import.process');

    // master unit
    Route::resource('/unit', 'UnitController');
    Route::get('pic/unit/{id}', 'UnitController@formImport');
    Route::post('pic/unit/process', 'UnitController@importProcess')
        ->name('unit.pic.process');

    // deployment
    // Route::resource('/deployment', 'DeploymentController');
    Route::get('/deployment', 'DeploymentController@index')
        ->name('deployment.index');
    Route::get('import/deployment', 'DeploymentController@formImport')
        ->name('deployment.import');
    Route::get('/deployment/edit/{id}', 'DeploymentController@edit');
    Route::get('/deployment/delete/{id}', 'DeploymentController@remove');
    Route::post('/deployment/update/', 'DeploymentController@update');
    Route::get('/deployment/carikodeunit/', 'DeploymentController@carikodeunit');
    Route::post('import/deployment/process', 'DeploymentController@importProcess')
        ->name('deployment.import.process');

    // deployment target
    Route::get('target/deployment', 'DeploymentTransactionController@index')
        ->name('deployment.target.index');
    Route::get('target/{id}/deployments', 'DeploymentTransactionController@create')
        ->name('deployment.target.create');
	Route::get('validasitarget/{id}/deployments', 'DeploymentTransactionController@validasitarget')
        ->name('deployment.target.validasitarget');
    Route::post('target/deployment','DeploymentTransactionController@store')
        ->name('deployment.store');
    Route::get('target/deployment/{id}/show','DeploymentTransactionController@show')
        ->name('deployment.target.show');
    Route::get('target/deployment/{id}/validasi/admin','DeploymentTransactionController@formValidasiAdmin')
        ->name('deployment.target.formvalidasiadmin');
    Route::get('deployments/unvalid/{id}','DeploymentTransactionController@Unvalidasi');
    Route::put('target/deployment/{id}/validasi/admin','DeploymentTransactionController@update')
        ->name('deployment.target.validasiadmin');
    Route::get('target/deployment/{id}/validasi/atasan','DeploymentTransactionController@formValidasiAtasan')
        ->name('deployment.target.formvalidasiatasan');
    Route::get('target/deployment/allvalidasitarget','DeploymentTransactionController@allvalidasitarget');
    Route::get('target/deployment/onevalidasitarget','DeploymentTransactionController@onevalidasitarget');
    Route::put('target/deployment/{id}/validasi/atasan','DeploymentTransactionController@validasiAtasan')
        ->name('deployment.target.validasiatasan');

    // deployment realization
    Route::get('realisasi/deployment','DeploymentRealizationController@index')
        ->name('deployment.realisasi.index');  
    Route::get('realisasi/hapusfile/','DeploymentRealizationController@hapusfile');
    Route::get('realisasi/deployment/{id}/show','DeploymentRealizationController@show')
        ->name('deployment.realisasi.show');  
	Route::post('realisasi/deployment','DeploymentRealizationController@store')
        ->name('deployment.realisasi.store');
	Route::post('realisasi/insrealisasi','DeploymentRealizationController@insrealisasi');
	Route::post('realisasi/insalasannya','DeploymentRealizationController@insalasan');
    Route::get('realisasi/validasi','DeploymentRealizationController@validasirealisasi');
    Route::get('realisasi/kembalikan','DeploymentRealizationController@kembalikanrealisasi');
    Route::get('realisasi/deployment/{id}/validasi','DeploymentRealizationController@formValidasi')
        ->name('deployment.realisasi.formvalidasi');
    Route::put('realisasi/deployment/{id}/validasi','DeploymentRealizationController@processValidasi')
        ->name('deployment.realisasi.validasi');
    Route::get('realisasi/validasiperbulan','DeploymentRealizationController@validasiperbulan');
     // deployment capaian
     Route::get('capaian/deployment','CapaianController@index')
     ->name('deployment.capaian.index');  
     Route::get('capaian/deployment/atasan','CapaianController@indexatasan');
     Route::get('capaian/deployment/laporancapaian','CapaianController@laporancapaian');
     Route::get('capaian/deployment/laporancapaianadmin/{kode?}/{nama?}/{tahun?}','CapaianController@laporancapaianadmin');
     Route::get('capaian/deployment/laporan/{kode?}/{tahun?}','CapaianController@laporan');
     Route::get('capaian/deployment/validasi/{kode?}/{tahun?}','CapaianController@laporan_validasi');
     Route::get('capaian/deployment/view_laporan/{kode?}/{tahun?}','CapaianController@view_laporan');
     Route::get('capaian/deployment/view_laporan_acc/{kode?}/{tahun?}','CapaianController@view_laporan_acc');
     
});


Route::get('/debug', 'DebugController@index');
Auth::routes();

app/Http/Controllers/backup/MateriRakoorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreMateri;
use Illuminate\Support\Facades\Auth;
use DataTables;
use App\Materi;
use App\File;
use App\User;

class MateriRakoorController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('materi-rakoor.materi-index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('materi-rakoor.materi-create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreMateri $request)
    {
        $materi = new Materi;
        $materi->date = $request->date;
        $materi->agenda_no = $request->agenda_no;
        $materi->username = Auth::user()->username;
        $materi->mulai = $request->jam_mulai;
        $materi->keluar = $request->jam_keluar;
        $materi->judul = $request->judul;
        $materi->no_dokumen = $request->no_dokumen;
        $materi->presenter = $request->presenter;
        $materi->save();
        
        if($request->file && $materi->id){
            foreach ($request->file as $key => $value) {
                $path          = $value->storeAs( 'public/files/'
                                . Auth::user()->username.'/'
                                . $request->tanggal.'/'
                                . $request->agenda, 
                                $value->getClientOriginalName() );
            
                $realName      = $value->getClientOriginalName();

                $file = new File;
                $file->materi_id = $materi->id;
                $file->name = $realName;
                $file->path = $path;
                $file->save();
            }
        }
        return redirect()->route('materi.index');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $administrator = Auth::user()->hasRole('administrator');
        $username = Auth::user()->username;
        $user_id = Auth::user()->id;
        /*
            Menampilkan data materi sesuai username di tabel materis
            atau
            Menampilkan data sesuai user_id pada tabel materi_user
            atau
            Menampilkan data sesuai user_id pada tabel reporters
        */
        $materi = Materi::whereHas('users',function($query) use ($user_id){
            $query->where('user_id',$user_id);
        })->orWhereHas('reporters',function($query) use ($user_id){
            $query->where('user_id',$user_id);
        })->orWhereHas('notulens',function($query) use ($user_id){
            $query->where('user_id',$user_id);
        })->orWhere(function($query) use ($username,$administrator) {
            if(!$administrator){
                $query->where('username',$username);
            }else{
                $query->where('username','<>',$username)
                ->orWhere('username',$username);
            }
        })->with(['files','reporters']);

        $ret = datatables($materi)
                ->addColumn('action', 'materi-rakoor._actionBtn')
                ->addColumn('tanggal', function($materi){
                    return $materi->dmyDate;
                })
                ->order(function ($query) {
                    $query->orderBy('date', 'desc');
                })
                ->toJson();
        
        return $ret;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $materi = Materi::where('id',$id)
            ->with('files')
            ->get();
        return view('materi-rakoor.materi-edit',compact('materi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $materi = Materi::find($id);
        $materi->date = $request->tanggal;
        $materi->agenda_no = $request->agenda;
        $materi->username = Auth::user()->username;
        $materi->mulai = $request->jam_mulai;
        $materi->keluar = $request->jam_keluar;
        $materi->judul = $request->judul;
        $materi->no_dokumen = $request->no_dokumen;
        $materi->presenter = $request->presenter;
        $materi->save();
        
        // if($request->file && $materi->id){
        //     foreach ($request->file as $key => $value) {
        //         $path          = $value->storeAs( 'public/files/'
        //                         . Auth::user()->username.'/'
        //                         . $request->tanggal.'/'
        //                         . $request->agenda, 
        //                         $value->getClientOriginalName() );
            
        //         $realName      = $value->getClientOriginalName();

        //         $file = new File;
        //         $file->materi_id = $materi->id;
        //         $file->name = $realName;
        //         $file->path = $path;
        //         $file->save();
        //     }
        // }
        return redirect()->route('materi.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $d = Materi::destroy($id);
        File::where('materi_id', $d)->delete();
        if($d){
            return redirect()->back();
        }
        
    }
}

app/Http/Controllers/backup/NotulenController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use DataTables;
use App\Reporter;
use App\Materi;
use App\User;
use App\Notulen;

class NotulenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('notulen.notulen-index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $materi = Materi::find($request->id);
        return view('notulen.notulen-create',compact('materi'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $notulen = new Notulen;
        $notulen->materi_id = $request->materi_id;
        $notulen->start = $request->start;
        $notulen->end = $request->end;
        $notulen->note = $request->note;
        $notulen->user_id = $request->pic;
        $notulen->save();

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $administrator = Auth::user()->hasRole('administrator');
        $username = Auth::user()->username;
        $user_id = Auth::user()->id;

        $materi = Materi::whereHas('reporters',function($query) use ($user_id,$administrator){
            $query->where('user_id',$user_id);
        })->orWhere(function($query) use ($username,$administrator) {
            if(!$administrator){
                $query->where('username',$username);
            }else{
                $query->where('username','<>',$username)
                ->orWhere('username',$username);
            }
        })->with(['reporters']);

        // return $materi->get();
        $ret = datatables($materi)
                ->addColumn('action','notulen._action')
                ->addColumn('tanggal', function($materi){
                    return $materi->dmyDate;
                })
                ->toJson();
        return $ret;
    }

    public function viewNotulen($id)
    {
        $notulen = Notulen::where('materi_id',$id)
        ->with(['users']);
        $ret = datatables($notulen)
                ->addColumn('pic',function($notulen){
                    return $notulen->users['name'];
                })
                ->addColumn('progres', function($notulen){
                    $count = $notulen->progress->count() ? $notulen->progress->count() : 1;
                    $sum = $notulen->progress->sum('realisasi') ? $notulen->progress->sum('realisasi') : 0;
                    return  round($sum/$count,2) . ' %';
                })
                ->addColumn('action','notulen._actionView')
                ->toJson();
        return $ret;
    }
    public function view($id)
    {
        $materi = Materi::find($id);
        return view('notulen.notulen-view',compact('id','materi'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function user(Request $request)
    {
        return User::getForSelect2($request);
    }
}

resources/views/backup/notulen/_action.blade.php
@foreach ($reporters as $item)
    @if (Auth::user()->id == $item['user_id'])
        <a class="btn btn-sm btn-primary" href="{{ route('notulen.create') }}?id={{$id}}">
            <i class="fa fa-pencil-square"></i>
            Catatan
        </a>
    @endif
    <a class="btn btn-sm btn-success" href="{{ route('notulen.view',$id) }}">
        <i class="fa fa-eye"></i>
        Lihat
    </a>
@endforeach

resources/views/backup/notulen/_actionView.blade.php
<a class="btn btn-sm btn-primary" href="{{ route('progres-kerja.view') }}/{{$id}}">
    <i class="fa fa-book"></i>
    Proker
</a>

resources/views/backup/notulen/notulen-create.blade.php
@extends('core-ui.layouts.app')

@push('style')
<link href="{{ asset('vendors/datetimepicker/jquery.datetimepicker.min.css') }}" rel="stylesheet">
<link href="{{ asset('vendors/select2/css/select2.min.css') }}" rel="stylesheet" />
<link href="{{ asset('vendors/select2/css/select2-bootstrap4.min.css') }}" rel="stylesheet" />
<link href="{{ asset('vendors/summernote-master/summernote-bs4.css') }}" rel="stylesheet" />
<link href="{{ asset('vendors/DataTables/datatables.min.css') }}" rel="stylesheet">
@endpush

@push('script')
<script src="{{ asset('vendors/datetimepicker/jquery.datetimepicker.full.min.js') }}"></script>
<script src="{{ asset('vendors/select2/js/select2.min.js') }}"></script>
<script src="{{ asset('vendors/summernote-master/summernote-bs4.min.js') }}"></script>
<script src="{{ asset('vendors/DataTables/datatables.min.js') }}"></script> 
<script>
$(document).ready(function() {
    $('#pic').select2({
        theme: 'bootstrap4',
        ajax: {
            url: "{{ route('notulen.user') }}",
            dataType: 'json'
        }
    });
    jQuery.datetimepicker.setLocale('id');

    jQuery('#start').datetimepicker({
        timepicker:false,
        mask:true,
        format:'d/m/Y'
    });
    jQuery('#end').datetimepicker({
        timepicker:false,
        mask:true,
        format:'d/m/Y'
    });

    $('#note').summernote({
        height: 90, 
    });

    $('#table').DataTable({
        responsive: true,
        processing: true,
        serverSide: true,
        ajax: "{{ route('notulen.viewNotulen',$materi->id) }}",
        columns: [
            {data: 'id',
                render: function(data, type, row, meta) {
                    return meta.row+1;
                }
            },
            {data: 'note'},
            {data: 'start',
                render: function(data, type, row, meta) {
                    return '<b>'+data+'</b> sd <b>'+row.end+'</b>';
                }
            },
            {data: 'pic'}

        ]
    });

});
function submit(){
    $('#form').submit();
}
</script>
@endpush

@include('core-ui.layouts._layout')

@section('content')
<div class="row justify-content-center">
    <div class="col m-3">
        <div class="card" style="width: 100%;">
            <div class="card-header">
                Notulen Rapat Koordinasi ( {{$materi->judul}} )
            </div>
            <div class="card-body">
                <form id="form" method="post" enctype="multipart/form-data" action="{{ route('notulen.store') }}">
                    <div class="row row-form">
                        @csrf
                        <input type="hidden" name="materi_id" value="{{$materi->id}}">
                        <div class="col-sm-6">
                            <label for="note">Catatan</label>
                            <textarea name="note" class="form-control mt-1 mb-2 border-primary" id="note" cols="30" rows="5"></textarea>
                        </div>
                        <div class="col-sm-6">
                            <div class="col-sm-12">
                                <label for="start">Dari</label>
                                <input type="text" name="start" class="form-control mb-1 border-primary" id="start" autocomplete="off">
                            </div>
                            <div class="col-sm-12">
                                <label for="end">Sampai</label>
                                <input type="text" name="end" class="form-control mb-1 border-primary" id="end" autocomplete="off">
                            </div>
                            <div class="col-sm-12">
                                <label for="pic">PIC</label>
                                <select class="select2 form-control mb-1" name="pic" id="pic" ></select>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="float-right mr-3 mt-2">
                    <a class="btn btn-danger btn-sm" href="{{ route('notulen.index') }}">
                        <i class="fa fa-arrow-left"></i>
                        Kembali
                    </a>

                    <button class="btn btn-primary btn-sm" type="button" onclick="submit()">
                        <i class="fa fa-save"></i>
                        Simpan
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col mx-3">
        <div class="card" style="width: 100%;">
            <div class="card-header">
                Data Notulen ( {{$materi->judul}} )
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover responsive no-wrap" id="table" width="100%">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Catatan</th>
                                <th>Due Date</th>
                                <th>PIC</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/backup/notulen/notulen-index.blade.php
@extends('core-ui.layouts.app')

@push('style')
<link href="{{ asset('vendors/DataTables/datatables.min.css') }}" rel="stylesheet">
@endpush

@push('script')
<script src="{{ asset('vendors/DataTables/datatables.min.js') }}"></script>
<script>
$(document).ready(function() {
    $('#notulen-table').DataTable({
        responsive: true,
        processing: true,
        serverSide: true,
        ajax: "{{ route('notulen.show','') }}/all",
        columns: [
            {data: 'id',
                render: function ( data, type, row, meta ) {
                    return meta.row+1;
                }
            },
            {data: 'judul'},
            {data: 'date',
                render: function ( data, type, row, meta ) {
                    return row.tanggal;
                }
            },
            {data: 'action'}
            
        ]
    });
});
</script>
@endpush

@include('core-ui.layouts._layout')

@section('content')
<div class="row justify-content-center">
    <div class="col m-3">
        <div class="card" style="width: 100%;">

            <div class="card-header">
                Notulen Rapat Koordinasi
            </div>
            
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table no-wrap" id="notulen-table" width="100%">
                        <thead>
                            <tr>
                                <th width="5%">No</th>
                                <th>Judul</th>
                                <th>Tanggal</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                    </table>
                </div>
                
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/backup/notulen/notulen-view.blade.php
@extends('core-ui.layouts.app')

@push('style')
<link href="{{ asset('vendors/DataTables/datatables.min.css') }}" rel="stylesheet">
@endpush

@push('script')
<script src="{{ asset('vendors/DataTables/datatables.min.js') }}"></script> 
<script>
$(document).ready(function() {
    $('#table').DataTable({
        responsive: true,
        processing: true,
        serverSide: true,
        ajax: "{{ route('notulen.viewNotulen',$id) }}",
        columns: [
            {data: 'id',
                render: function(data, type, row, meta) {
                    return meta.row+1;
                }
            },
            {data: 'note'},
            {data: 'start',
                render: function(data, type, row, meta) {
                    return '<b>'+data+'</b> sd <b>'+row.end+'</b>';
                }
            },
            {data: 'pic'},
            {data: 'progres'},
            {data: 'action'}

        ]
    });

});
</script>
@endpush

@include('core-ui.layouts._layout')

@section('content')
<div class="row justify-content-center">
    <div class="col m-3">
        <div class="card" style="width: 100%;">
            <div class="card-header">
                {{ $materi->judul }}
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover responsive no-wrap table-striped" id="table" width="100%">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Catatan</th>
                                <th>Due Date</th>
                                <th>PIC</th>
                                <th>Progres</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection