routes/dashboard.php
<?php

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('a/{personnel_no}/', 'Auth\LoginController@programaticallyEmployeeLogin')->name('login.a');
    

Route::get('/config-cache', function() {
    Artisan::call('config:cache');
    return "Cache is cleared";
});
Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});
Route::get('/', function () {
    if (!Auth::user()) {
        // untuk virutal host
        // return redirect()->route('login');
        return redirect()->away('https://sso.krakatausteel.com');

        // jika tidak menggukalan virtual host
        // return redirect()->guest('/public/login');
    } else {
        
        return redirect()->route('dashboard');
    }
});



Route::group(['middleware' => ['auth','role:administrator']], function () {
    Route::resource('user', 'UserController')->parameters(['user' => 'id']);
});

Route::group(['middleware' => ['auth','role:administrator|admin']], function () {
    Route::resource('materi', 'MateriRakoorController')->parameters(['materi' => 'id']);
    
    Route::get('partisipan/user', 'PartisipanController@user')->name('partisipan.user');
    Route::get('ambil_unit/performance', 'UnitController@ambil_unit');
    Route::resource('partisipan', 'PartisipanController')->parameters(['partisipan' => 'id']);
    
    Route::get('notulis/user', 'NotulisController@user')->name('notulis.user');
    Route::resource('notulis', 'NotulisController')->parameters(['notulis' => 'id']);
});

Route::group(['middleware' => ['auth','role:notulis|administrator|admin']], function () {
    Route::get('notulen/user/{q?}', 'NotulenController@user')->name('notulen.user');
    Route::resource('notulen', 'NotulenController')->parameters(['notulen' => 'id']);
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/unit', 'UnitController');

    // master kpi
    // Route::resource('/kpi', 'KpiController');
    Route::get('/dashboard/{kode?}/{nama?}/{tahun?}/{bulan?}', 'HomeController@index');
    Route::get('/kpi', 'KpiController@index')
        ->name('kpi.index');
    Route::get('import/kpi', 'KpiController@formImport')
        ->name('kpi.import');
    Route::get('kpi/{id}', 'KpiController@edit')
        ->name('kpi.edit');
    Route::put('kpi/{id}', 'KpiController@update')
        ->name('kpi.update');
    Route::post('/import/kpi/process','KpiController@importProcess')
        ->name('kpi.import.process');

    // master unit
    Route::resource('/unit', 'UnitController');
    Route::get('pic/unit/{id}', 'UnitController@formImport');
    Route::post('pic/unit/process', 'UnitController@importProcess')
        ->name('unit.pic.process');

    // deployment
    // Route::resource('/deployment', 'DeploymentController');
    Route::get('/deployment', 'DeploymentController@index')
        ->name('deployment.index');
    Route::get('import/deployment', 'DeploymentController@formImport')
        ->name('deployment.import');
    Route::get('/deployment/edit/{id}', 'DeploymentController@edit');
    Route::get('/deployment/delete/{id}', 'DeploymentController@remove');
    Route::post('/deployment/update/', 'DeploymentController@update');
    Route::get('/deployment/carikodeunit/', 'DeploymentController@carikodeunit');
    Route::post('import/deployment/process', 'DeploymentController@importProcess')
        ->name('deployment.import.process');

    // deployment target
    Route::get('target/deployment', 'DeploymentTransactionController@index')
        ->name('deployment.target.index');
    Route::get('target/{id}/deployments', 'DeploymentTransactionController@create')
        ->name('deployment.target.create');
	Route::get('validasitarget/{id}/deployments', 'DeploymentTransactionController@validasitarget')
        ->name('deployment.target.validasitarget');
    Route::post('target/deployment','DeploymentTransactionController@store')
        ->name('deployment.store');
    Route::get('target/deployment/{id}/show','DeploymentTransactionController@show')
        ->name('deployment.target.show');
    Route::get('target/deployment/{id}/validasi/admin','DeploymentTransactionController@formValidasiAdmin')
        ->name('deployment.target.formvalidasiadmin');
    Route::get('deployments/unvalid/{id}','DeploymentTransactionController@Unvalidasi');
    Route::put('target/deployment/{id}/validasi/admin','DeploymentTransactionController@update')
        ->name('deployment.target.validasiadmin');
    Route::get('target/deployment/{id}/validasi/atasan','DeploymentTransactionController@formValidasiAtasan')
        ->name('deployment.target.formvalidasiatasan');
    Route::get('target/deployment/allvalidasitarget','DeploymentTransactionController@allvalidasitarget');
    Route::get('target/deployment/onevalidasitarget','DeploymentTransactionController@onevalidasitarget');
    Route::put('target/deployment/{id}/validasi/atasan','DeploymentTransactionController@validasiAtasan')
        ->name('deployment.target.validasiatasan');

    // deployment realization
    Route::get('realisasi/deployment','DeploymentRealizationController@index')
        ->name('deployment.realisasi.index');  
    Route::get('realisasi/hapusfile/','DeploymentRealizationController@hapusfile');
    Route::get('realisasi/deployment/{id}/show','DeploymentRealizationController@show')
        ->name('deployment.realisasi.show');  
	Route::post('realisasi/deployment','DeploymentRealizationController@store')
        ->name('deployment.realisasi.store');
	Route::post('realisasi/insrealisasi','DeploymentRealizationController@insrealisasi');
	Route::post('realisasi/insalasannya','DeploymentRealizationController@insalasan');
    Route::get('realisasi/validasi','DeploymentRealizationController@validasirealisasi');
    Route::get('realisasi/kembalikan','DeploymentRealizationController@kembalikanrealisasi');
    Route::get('realisasi/deployment/{id}/validasi','DeploymentRealizationController@formValidasi')
        ->name('deployment.realisasi.formvalidasi');
    Route::put('realisasi/deployment/{id}/validasi','DeploymentRealizationController@processValidasi')
        ->name('deployment.realisasi.validasi');
    Route::get('realisasi/validasiperbulan','DeploymentRealizationController@validasiperbulan');
     // deployment capaian
     Route::get('capaian/deployment','CapaianController@index')
     ->name('deployment.capaian.index');  
     Route::get('capaian/deployment/atasan','CapaianController@indexatasan');
     Route::get('capaian/deployment/laporancapaian','CapaianController@laporancapaian');
     Route::get('capaian/deployment/laporancapaianadmin/{kode?}/{nama?}/{tahun?}','CapaianController@laporancapaianadmin');
     Route::get('capaian/deployment/laporan/{kode?}/{tahun?}','CapaianController@laporan');
     Route::get('capaian/deployment/validasi/{kode?}/{tahun?}','CapaianController@laporan_validasi');
     Route::get('capaian/deployment/view_laporan/{kode?}/{tahun?}','CapaianController@view_laporan');
     Route::get('capaian/deployment/view_laporan_acc/{kode?}/{tahun?}','CapaianController@view_laporan_acc');
     
});


Route::get('/debug', 'DebugController@index');
Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable,HasRoles;
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'email', 'password', 'kode_unit',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function materis()
    {
        return $this->belongsToMany('App\Materi');
    }

    public function reporters()
    {
        return $this->hasMany('App\Reporter','user_id');
    }

    public function notulens()
    {
        return $this->hasMany('App\Notulen','user_id');
    }

    public function progresses()
    {
        return $this->hasMany('App\Progress','user_id');
    }

    public function unitkerja() 
    {
        return $this->hasMany('App\Unit', 'username', 'nik_atasan');
    }
    public function scopeGetForSelect2($query,$request)
    {   
        $auth = Auth::user()->username;
        // dapatkan semua username yang mempunyai role administrator
        // dan username user yang login
        $filtterUser = User::select('username')
            ->role('administrator')
            // ->orWhere('username',$auth)
            ->get();
        
        // tampilkan data username dari table users yang role selain administrator
        $user = $query->where(function ($query) use ($filtterUser,$request){
                $query->whereNotIn('username',$filtterUser)
                ->where('name', 'like','%'.$request->q.'%');
            })
            ->limit(15)
            ->get()
            ->map(function ($value,$key) {
                return ['id' => $value->id, 'text'=>$value->name];
            });
        $select2 = ['results'=>$user];
        return $select2;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Hash;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\User;
use App\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.user-index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   $role = Role::whereNotIn('id',['1','4','5'])->get();
        return view('user.user-create',compact('role') );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = new User();
        $user->name = $request->nama;
        $user->email = $request->email;
        $user->username = Str::before($request->email, '@');
        $user->password = Hash::make($request->password);
        $user->save();
        $user->assignRole($request->role);

        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::with('roles');

        $ret = datatables($user)
            ->addColumn('roles', 'user._listRole')
            ->addColumn('action', 'user._actionBtn')
            ->toJson();
        return $ret;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::where('id',$id)->with('roles')->first();
        $role = Role::whereNotIn('id',['1','4','5'])->get();
        return view('user.user-edit',compact('user','role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->name = $request->nama;
        $user->email = $request->email;
        $user->username = Str::before($request->email, '@');
        $user->save();

        $user->removeRole('admin');
        $user->removeRole('user');
        $user->assignRole($request->role);
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::destroy($id);
        return redirect()->back();
    }
}

resources/views/user/_actionBtn.blade.php
@if ($username !== 'administrator')
    <a href="{{ route('user.edit',$id) }}" class="btn btn-warning btn-sm my-1">
        <i class="fa fa-pencil-square"></i>
        Edit
    </a>

    <button class="btn btn-danger btn-sm my-1" data-toggle="modal" data-target="#modal-delete{{$id}}">
        <i class="fa fa-trash"></i>
        Hapus
    </button>
    <div  id="modal-delete{{$id}}" class="modal fade bd-example-modal-sm"  data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm ">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title">Hapus?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <form action="{{ route('user.destroy',$id) }}" method="post" class="d-flex justify-content-center">
                        {{ method_field('DELETE') }}
                        @csrf
                        <button class="btn btn-primary btn-sm mr-1" type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-refresh"></i>
                            TIDAK
                        </button>
                        <button class="btn btn-outline-danger btn-sm ml-1">
                            <i class="fa fa-remove"></i>
                            YA
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endif

resources/views/user/_listRole.blade.php
@foreach ($roles as $item)
    <span class="badge badge-dark">
        {{ $item['name'] }} 
    </span>
@endforeach

resources/views/user/user-create.blade.php
@extends('core-ui.layouts.app')

@push('style')
<style></style>
@endpush

@push('script')

@endpush

@include('core-ui.layouts._layout')

@section('content')
<input type="hidden" id="index" value="1">

<div class="container mt-1">
    <div class="row justify-content-center">
        <div class="col">
            <div class="card" style="width: 100%;">

                <div class="card-header">
                    Tambah Data User {{ config('app.name') }}
                </div>
                
                <div class="card-body">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <form method="post" enctype="multipart/form-data" action="{{ route('user.store') }}">
                        @csrf
                        <div class="form-group row">
                            <label for="nama" class="col-sm-2 col-form-label">Nama : </label>
                            <div class="col-sm-10">
                                <input type="text" name="nama" value="{{ old('nama') }}" class="form-control" id="nama" placeholder="Nama" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email" class="col-sm-2 col-form-label">Email : </label>
                            <div class="col-sm-10">
                                <input type="email" name="email" value="{{ old('email') }}" class="form-control" id="email" placeholder="Email" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="password" class="col-sm-2 col-form-label">Password : </label>
                            <div class="col-sm-10">
                                <input type="text" name="password" value="{{ old('password')?old('password'):'initial.1' }}" class="form-control" id="password" placeholder="Password" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="role" class="col-sm-2 col-form-label">Role : </label>
                            <div class="col-sm-10">
                                @foreach ($role as $key => $item)
                                    <label>
                                        <input type="radio" name="role" value="{{$item->name}}" required>
                                        {{$item->name}}
                                    </label><br>
                                @endforeach
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <a class="btn btn-outline-danger" href="{{ Route('user.index') }}">
                                    <i class="fa fa-arrow-left"></i>
                                    Kembali
                                </a>
                                <button type="reset" class="btn btn-outline-warning">
                                    <i class="fa fa-recycle"></i>
                                    Bersihkan
                                </button>
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-save"></i>
                                    Simpan
                                </button>
                            </div>
                        </div>
                    </form>

                    <div class="alert alert-info">
                        <p>
                            Role <b>Admin</b> adalah role yang bertugas untuk membuat jadwal rapat, 
                            menambahlan <b>partisipan</b> dan menunjuk <b>notulis</b> <br>
                            
                            Role <b>User</b> adalah minimal role yang bisa mengakses aplikasi rakordir
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/user-edit.blade.php
@extends('core-ui.layouts.app')

@push('style')
<style></style>
@endpush

@push('script')

@endpush

@include('core-ui.layouts._layout')

@section('content')
<input type="hidden" id="index" value="1">

<div class="container mt-1">
    <div class="row justify-content-center">
        <div class="col">
            <div class="card" style="width: 100%;">

                <div class="card-header">
                    Edit Data User Rakordir
                </div>
                
                <div class="card-body">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <form method="post" enctype="multipart/form-data" action="{{ route('user.update',$user->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="nama" class="col-sm-2 col-form-label">Nama : </label>
                            <div class="col-sm-10">
                                <input type="text" name="nama" value="{{ $user->name }}" class="form-control" id="nama" placeholder="Nama" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email" class="col-sm-2 col-form-label">Email : </label>
                            <div class="col-sm-10">
                                <input type="email" name="email" value="{{ $user->email }}" class="form-control" id="email" placeholder="Email" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="role" class="col-sm-2 col-form-label">Role : </label>
                            <div class="col-sm-10">
                                @foreach ($role as $key => $item)
                                    @php($cek = '')
                                    @foreach ($user->roles->whereIn('id',['2','3'])->toArray() as $itemx)
                                        @if ($itemx['id'] == $item->id)
                                            @php($cek = 'checked')
                                        @endif
                                    @endforeach

                                    <label>
                                        <input type="radio" name="role" value="{{$item->name}}" {{ $cek }}>
                                        {{$item->name}}
                                    </label><br>
                                @endforeach

                                
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <a class="btn btn-outline-danger" href="{{ Route('user.index') }}">
                                    <i class="fa fa-arrow-left"></i>
                                    Kembali
                                </a>
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-save"></i>
                                    Simpan
                                </button>
                            </div>
                        </div>
                    </form>

                    {{-- <div class="alert alert-info">
                        <p>
                            Role <b>Admin</b> adalah role yang bertugas untuk membuat jadwal rapat, 
                            menambahlan <b>partisipan</b> dan menunjuk <b>notulis</b> <br>
                            
                            Role <b>User</b> adalah minimal role yang bisa mengakses aplikasi rakordir
                        </p>
                    </div> --}}
                </div>

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/user-index.blade.php
@extends('core-ui.layouts.app') @push('style')
<link href="{{ asset('vendors/DataTables/datatables.min.css') }}" rel="stylesheet">
<style></style>

@endpush @push('script')
<script src="{{ asset('vendors/DataTables/datatables.min.js') }}"></script>
<script>
$(document).ready(function() {
    $('#user-table').DataTable({
        responsive: true,
        processing: true,
        serverSide: true,
        ajax: "{{ route('user.show','') }}/all",
        columns: [
            {data: 'id',
                render: function(data, type, row, meta) {
                    return meta.row+1;
                }
            },
            {data: 'name'},
            {data: 'username'},
            {data: 'email'},
            {data: 'roles'},
            {data: 'action'}
        ]
    });
});
</script>

@endpush
    @include('core-ui.layouts._layout') 
@section('content')
<div class="row justify-content-center">
    <div class="col m-3">
        <div class="card" style="width: 100%;">

            <div class="card-header">
                User Sistem Informasi Performance
                <div class="float-right">
                    <a class="btn btn-outline-danger btn-sm mx-1" href="{{ route('user.create') }}">
                        <i class="fa fa-plus-circle fa-lg"></i>
                        Tambah Data User
                    </a>
                </div>
            </div>

            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover responsive no-wrap" id="user-table" width="100%">
                        <thead>
                            <tr>
                                <th data-priority="1">No</th>
                                <th>Nama</th>
                                <th>User Name</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection