routes/dashboard.php
<?php

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('a/{personnel_no}/', 'Auth\LoginController@programaticallyEmployeeLogin')->name('login.a');
    

Route::get('/config-cache', function() {
    Artisan::call('config:cache');
    return "Cache is cleared";
});
Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});
Route::get('/', function () {
    if (!Auth::user()) {
        // untuk virutal host
        // return redirect()->route('login');
        return redirect()->away('https://sso.krakatausteel.com');

        // jika tidak menggukalan virtual host
        // return redirect()->guest('/public/login');
    } else {
        
        return redirect()->route('dashboard');
    }
});



Route::group(['middleware' => ['auth','role:administrator']], function () {
    Route::resource('user', 'UserController')->parameters(['user' => 'id']);
});

Route::group(['middleware' => ['auth','role:administrator|admin']], function () {
    Route::resource('materi', 'MateriRakoorController')->parameters(['materi' => 'id']);
    
    Route::get('partisipan/user', 'PartisipanController@user')->name('partisipan.user');
    Route::get('ambil_unit/performance', 'UnitController@ambil_unit');
    Route::resource('partisipan', 'PartisipanController')->parameters(['partisipan' => 'id']);
    
    Route::get('notulis/user', 'NotulisController@user')->name('notulis.user');
    Route::resource('notulis', 'NotulisController')->parameters(['notulis' => 'id']);
});

Route::group(['middleware' => ['auth','role:notulis|administrator|admin']], function () {
    Route::get('notulen/user/{q?}', 'NotulenController@user')->name('notulen.user');
    Route::resource('notulen', 'NotulenController')->parameters(['notulen' => 'id']);
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/unit', 'UnitController');

    // master kpi
    // Route::resource('/kpi', 'KpiController');
    Route::get('/dashboard/{kode?}/{nama?}/{tahun?}/{bulan?}', 'HomeController@index');
    Route::get('/kpi', 'KpiController@index')
        ->name('kpi.index');
    Route::get('import/kpi', 'KpiController@formImport')
        ->name('kpi.import');
    Route::get('kpi/{id}', 'KpiController@edit')
        ->name('kpi.edit');
    Route::put('kpi/{id}', 'KpiController@update')
        ->name('kpi.update');
    Route::post('/import/kpi/process','KpiController@importProcess')
        ->name('kpi.import.process');

    // master unit
    Route::resource('/unit', 'UnitController');
    Route::get('pic/unit/{id}', 'UnitController@formImport');
    Route::post('pic/unit/process', 'UnitController@importProcess')
        ->name('unit.pic.process');

    // deployment
    // Route::resource('/deployment', 'DeploymentController');
    Route::get('/deployment', 'DeploymentController@index')
        ->name('deployment.index');
    Route::get('import/deployment', 'DeploymentController@formImport')
        ->name('deployment.import');
    Route::get('/deployment/edit/{id}', 'DeploymentController@edit');
    Route::get('/deployment/delete/{id}', 'DeploymentController@remove');
    Route::post('/deployment/update/', 'DeploymentController@update');
    Route::get('/deployment/carikodeunit/', 'DeploymentController@carikodeunit');
    Route::post('import/deployment/process', 'DeploymentController@importProcess')
        ->name('deployment.import.process');

    // deployment target
    Route::get('target/deployment', 'DeploymentTransactionController@index')
        ->name('deployment.target.index');
    Route::get('target/{id}/deployments', 'DeploymentTransactionController@create')
        ->name('deployment.target.create');
	Route::get('validasitarget/{id}/deployments', 'DeploymentTransactionController@validasitarget')
        ->name('deployment.target.validasitarget');
    Route::post('target/deployment','DeploymentTransactionController@store')
        ->name('deployment.store');
    Route::get('target/deployment/{id}/show','DeploymentTransactionController@show')
        ->name('deployment.target.show');
    Route::get('target/deployment/{id}/validasi/admin','DeploymentTransactionController@formValidasiAdmin')
        ->name('deployment.target.formvalidasiadmin');
    Route::get('deployments/unvalid/{id}','DeploymentTransactionController@Unvalidasi');
    Route::put('target/deployment/{id}/validasi/admin','DeploymentTransactionController@update')
        ->name('deployment.target.validasiadmin');
    Route::get('target/deployment/{id}/validasi/atasan','DeploymentTransactionController@formValidasiAtasan')
        ->name('deployment.target.formvalidasiatasan');
    Route::get('target/deployment/allvalidasitarget','DeploymentTransactionController@allvalidasitarget');
    Route::get('target/deployment/onevalidasitarget','DeploymentTransactionController@onevalidasitarget');
    Route::put('target/deployment/{id}/validasi/atasan','DeploymentTransactionController@validasiAtasan')
        ->name('deployment.target.validasiatasan');

    // deployment realization
    Route::get('realisasi/deployment','DeploymentRealizationController@index')
        ->name('deployment.realisasi.index');  
    Route::get('realisasi/hapusfile/','DeploymentRealizationController@hapusfile');
    Route::get('realisasi/deployment/{id}/show','DeploymentRealizationController@show')
        ->name('deployment.realisasi.show');  
	Route::post('realisasi/deployment','DeploymentRealizationController@store')
        ->name('deployment.realisasi.store');
	Route::post('realisasi/insrealisasi','DeploymentRealizationController@insrealisasi');
	Route::post('realisasi/insalasannya','DeploymentRealizationController@insalasan');
    Route::get('realisasi/validasi','DeploymentRealizationController@validasirealisasi');
    Route::get('realisasi/kembalikan','DeploymentRealizationController@kembalikanrealisasi');
    Route::get('realisasi/deployment/{id}/validasi','DeploymentRealizationController@formValidasi')
        ->name('deployment.realisasi.formvalidasi');
    Route::put('realisasi/deployment/{id}/validasi','DeploymentRealizationController@processValidasi')
        ->name('deployment.realisasi.validasi');
    Route::get('realisasi/validasiperbulan','DeploymentRealizationController@validasiperbulan');
     // deployment capaian
     Route::get('capaian/deployment','CapaianController@index')
     ->name('deployment.capaian.index');  
     Route::get('capaian/deployment/atasan','CapaianController@indexatasan');
     Route::get('capaian/deployment/laporancapaian','CapaianController@laporancapaian');
     Route::get('capaian/deployment/laporancapaianadmin/{kode?}/{nama?}/{tahun?}','CapaianController@laporancapaianadmin');
     Route::get('capaian/deployment/laporan/{kode?}/{tahun?}','CapaianController@laporan');
     Route::get('capaian/deployment/validasi/{kode?}/{tahun?}','CapaianController@laporan_validasi');
     Route::get('capaian/deployment/view_laporan/{kode?}/{tahun?}','CapaianController@view_laporan');
     Route::get('capaian/deployment/view_laporan_acc/{kode?}/{tahun?}','CapaianController@view_laporan_acc');
     
});


Route::get('/debug', 'DebugController@index');
Auth::routes();

app/Http/Controllers/backup/MateriRakoorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreMateri;
use Illuminate\Support\Facades\Auth;
use DataTables;
use App\Materi;
use App\File;
use App\User;

class MateriRakoorController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('materi-rakoor.materi-index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('materi-rakoor.materi-create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreMateri $request)
    {
        $materi = new Materi;
        $materi->date = $request->date;
        $materi->agenda_no = $request->agenda_no;
        $materi->username = Auth::user()->username;
        $materi->mulai = $request->jam_mulai;
        $materi->keluar = $request->jam_keluar;
        $materi->judul = $request->judul;
        $materi->no_dokumen = $request->no_dokumen;
        $materi->presenter = $request->presenter;
        $materi->save();
        
        if($request->file && $materi->id){
            foreach ($request->file as $key => $value) {
                $path          = $value->storeAs( 'public/files/'
                                . Auth::user()->username.'/'
                                . $request->tanggal.'/'
                                . $request->agenda, 
                                $value->getClientOriginalName() );
            
                $realName      = $value->getClientOriginalName();

                $file = new File;
                $file->materi_id = $materi->id;
                $file->name = $realName;
                $file->path = $path;
                $file->save();
            }
        }
        return redirect()->route('materi.index');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $administrator = Auth::user()->hasRole('administrator');
        $username = Auth::user()->username;
        $user_id = Auth::user()->id;
        /*
            Menampilkan data materi sesuai username di tabel materis
            atau
            Menampilkan data sesuai user_id pada tabel materi_user
            atau
            Menampilkan data sesuai user_id pada tabel reporters
        */
        $materi = Materi::whereHas('users',function($query) use ($user_id){
            $query->where('user_id',$user_id);
        })->orWhereHas('reporters',function($query) use ($user_id){
            $query->where('user_id',$user_id);
        })->orWhereHas('notulens',function($query) use ($user_id){
            $query->where('user_id',$user_id);
        })->orWhere(function($query) use ($username,$administrator) {
            if(!$administrator){
                $query->where('username',$username);
            }else{
                $query->where('username','<>',$username)
                ->orWhere('username',$username);
            }
        })->with(['files','reporters']);

        $ret = datatables($materi)
                ->addColumn('action', 'materi-rakoor._actionBtn')
                ->addColumn('tanggal', function($materi){
                    return $materi->dmyDate;
                })
                ->order(function ($query) {
                    $query->orderBy('date', 'desc');
                })
                ->toJson();
        
        return $ret;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $materi = Materi::where('id',$id)
            ->with('files')
            ->get();
        return view('materi-rakoor.materi-edit',compact('materi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $materi = Materi::find($id);
        $materi->date = $request->tanggal;
        $materi->agenda_no = $request->agenda;
        $materi->username = Auth::user()->username;
        $materi->mulai = $request->jam_mulai;
        $materi->keluar = $request->jam_keluar;
        $materi->judul = $request->judul;
        $materi->no_dokumen = $request->no_dokumen;
        $materi->presenter = $request->presenter;
        $materi->save();
        
        // if($request->file && $materi->id){
        //     foreach ($request->file as $key => $value) {
        //         $path          = $value->storeAs( 'public/files/'
        //                         . Auth::user()->username.'/'
        //                         . $request->tanggal.'/'
        //                         . $request->agenda, 
        //                         $value->getClientOriginalName() );
            
        //         $realName      = $value->getClientOriginalName();

        //         $file = new File;
        //         $file->materi_id = $materi->id;
        //         $file->name = $realName;
        //         $file->path = $path;
        //         $file->save();
        //     }
        // }
        return redirect()->route('materi.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $d = Materi::destroy($id);
        File::where('materi_id', $d)->delete();
        if($d){
            return redirect()->back();
        }
        
    }
}

app/Http/Controllers/backup/NotulenController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use DataTables;
use App\Reporter;
use App\Materi;
use App\User;
use App\Notulen;

class NotulenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('notulen.notulen-index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $materi = Materi::find($request->id);
        return view('notulen.notulen-create',compact('materi'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $notulen = new Notulen;
        $notulen->materi_id = $request->materi_id;
        $notulen->start = $request->start;
        $notulen->end = $request->end;
        $notulen->note = $request->note;
        $notulen->user_id = $request->pic;
        $notulen->save();

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $administrator = Auth::user()->hasRole('administrator');
        $username = Auth::user()->username;
        $user_id = Auth::user()->id;

        $materi = Materi::whereHas('reporters',function($query) use ($user_id,$administrator){
            $query->where('user_id',$user_id);
        })->orWhere(function($query) use ($username,$administrator) {
            if(!$administrator){
                $query->where('username',$username);
            }else{
                $query->where('username','<>',$username)
                ->orWhere('username',$username);
            }
        })->with(['reporters']);

        // return $materi->get();
        $ret = datatables($materi)
                ->addColumn('action','notulen._action')
                ->addColumn('tanggal', function($materi){
                    return $materi->dmyDate;
                })
                ->toJson();
        return $ret;
    }

    public function viewNotulen($id)
    {
        $notulen = Notulen::where('materi_id',$id)
        ->with(['users']);
        $ret = datatables($notulen)
                ->addColumn('pic',function($notulen){
                    return $notulen->users['name'];
                })
                ->addColumn('progres', function($notulen){
                    $count = $notulen->progress->count() ? $notulen->progress->count() : 1;
                    $sum = $notulen->progress->sum('realisasi') ? $notulen->progress->sum('realisasi') : 0;
                    return  round($sum/$count,2) . ' %';
                })
                ->addColumn('action','notulen._actionView')
                ->toJson();
        return $ret;
    }
    public function view($id)
    {
        $materi = Materi::find($id);
        return view('notulen.notulen-view',compact('id','materi'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function user(Request $request)
    {
        return User::getForSelect2($request);
    }
}

resources/views/backup/partisipan/_actionBtn.blade.php
@if ( $username == Auth::user()->username )
    @can('create partisipans')
    <a href="{{ route('partisipan.create',['id'=>$id]) }}" class="btn btn-primary btn-sm my-1">
        <i class="fa fa-user-circle"></i>
        Partisipan (+)
    </a>
    @endcan
    @can('create notulens')
    <a href="{{ route('notulis.create',['id'=>$id]) }}" class="btn btn-success btn-sm my-1">
        <i class="fa fa-pencil-square"></i>
        Notulis (+)
    </a>
    @endcan
@endif

resources/views/backup/partisipan/_listNotulis.blade.php
<ul style="font-weight: bold">
    @foreach ($reporters as $item)
        @if ($item['users']['name'])
        <li>
            @can('delete notulens')
                @if ( $username == Auth::user()->username )
                    <button class="btn btn-warning btn-sm my-1" data-toggle="modal" data-target=".notulis{{$item['id']}}">
                        <i class="fa fa-times-circle"></i>
                    </button>
                @endif
                <div  id="modal-delete" class="modal fade notulis{{$item['id']}}"  data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-sm ">
                        <div class="modal-content">

                            <div class="modal-header">
                                <h5 class="modal-title">Hapus Notulis ?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <div class="modal-body">
                                <form action="{{ route('notulis.destroy',$item['id']) }}" method="post" class="d-flex justify-content-center">
                                    {{ method_field('DELETE') }}
                                    @csrf
                                    <button class="btn btn-primary btn-sm mr-1" type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <i class="fa fa-refresh"></i>
                                        TIDAK
                                    </button>
                                    <button class="btn btn-outline-danger btn-sm ml-1">
                                        <i class="fa fa-remove"></i>
                                        YA
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            @endcan
            {{ $item['users']['name'] }}
        </li>
        @endif
    @endforeach
</ul>

resources/views/backup/partisipan/_listPartisipan.blade.php
<ol style="font-weight: bold">
    @foreach ($users as $item)
        <li>
            @can('delete partisipans')
                @if ( $username == Auth::user()->username )
                    <button class="btn btn-danger btn-sm my-1" data-toggle="modal" data-target=".partisipan{{$id}}{{$item['id']}}">
                        <i class="fa fa-times-circle"></i>
                    </button>
                @endif
                <div  id="modal-delete" class="modal partisipan{{$id}}{{$item['id']}}"  data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-sm ">
                        <div class="modal-content">

                            <div class="modal-header">
                                <h5 class="modal-title">Hapus Partisipan {{ ucfirst($item['name']) }} ?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <div class="modal-body">
                                <form action="{{ route('partisipan.destroy',$id.'-'.$item['id']) }}" method="post" class="d-flex justify-content-center">
                                    {{ method_field('DELETE') }}
                                    @csrf
                                    <button class="btn btn-primary btn-sm mr-1" type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <i class="fa fa-refresh"></i>
                                        TIDAK
                                    </button>
                                    <button class="btn btn-outline-danger btn-sm ml-1">
                                        <i class="fa fa-remove"></i>
                                        YA
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            @endcan
            {{ ucfirst($item['name']) }}
        </li>
    @endforeach
</ol>

resources/views/backup/partisipan/partisipan-create.blade.php
@extends('core-ui.layouts.app')

@push('style')
<link href="{{ asset('vendors/select2/css/select2.min.css') }}" rel="stylesheet" />
<link href="{{ asset('vendors/select2/css/select2-bootstrap4.min.css') }}" rel="stylesheet" />
@endpush

@push('script')
<script src="{{ asset('vendors/select2/js/select2.min.js') }}"></script>
<script>
$(document).ready(function () {
    $('#partisipan').select2({
        theme: 'bootstrap4',
        ajax: {
            url: "{{ route('partisipan.user') }}",
            dataType: 'json'
        }
    });
    $('.select2-container').addClass('mb-2');
});
function addFile(){
    var index = 1;
    $('#index').val(index+1);
    var newIndex = $('#index').val();
    var file = '<select class="select2 form-control mb-1" name="partisipan[]" id="partisipan'+newIndex+'"></select>';
    var button = '<button class="btn btn-danger mb-2 btn-block" onclick="removeButton('+newIndex+')" id="button'+newIndex+'" type="button"><i class="fa fa-minus-circle fa-lg"></i></button>';
    $('.addfile').append(file);
    $('.addButton').append(button);

    $("#partisipan"+newIndex+"").select2({
        theme: 'bootstrap4',
        ajax: {
            url: "{{ route('partisipan.user') }}",
            dataType: 'json'
        }
    });
    $('.select2-container').addClass('mb-2');
}
function removeButton(params) {
    $('.addButton').find('#button'+params).remove();
    $('.addfile').find('#file'+params).remove();
}
</script>
@endpush

@include('core-ui.layouts._layout')

@section('content')
<input type="hidden" id="index" value="1">
<div class="row justify-content-center">
    <div class="col m-3">
        <div class="card" style="width: 100%;">

            <div class="card-header">
                Tambah Data Partisipan Rapat Koordinasi
            </div>
            
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <form method="post" enctype="multipart/form-data" action="{{ route('partisipan.store') }}">
                    @csrf
                    <div class="form-group row">
                        <label for="judul" class="col-sm-2 col-form-label">Judul Rakoor: </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" readonly value="{{ $materi->judul }}">
                            <input type="hidden" class="form-control" value="{{ $materi->id }}" name="judul" id="judul">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="partisipan" class="col-sm-2 col-form-label">Partisipan : </label>
                        <div class="col-10 addfile">
                            <select class="select2 form-control" name="partisipan[]" id="partisipan" multiple="multiple"></select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-10">
                            <a class="btn btn-outline-danger" href="{{ Route('partisipan.index') }}">
                                <i class="fa fa-arrow-left"></i>
                                Kembali
                            </a>
                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-save"></i>
                                Simpan
                            </button>
                            
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/backup/partisipan/partisipan-index.blade.php
@extends('core-ui.layouts.app') @push('style')
<link href="{{ asset('vendors/DataTables/datatables.min.css') }}" rel="stylesheet">
<style></style>

@endpush @push('script')
<script src="{{ asset('vendors/DataTables/datatables.min.js') }}"></script>
<script>
$(document).ready(function() {
    $('#table').DataTable({
        responsive: true,
        processing: true,
        serverSide: true,
        ajax: "{{ route('partisipan.show','') }}/all",
        columns: [
            {data: 'id',
                render: function(data, type, row, meta) {
                    return meta.row+1;
                }
            },
            {data: 'judul'},
            {data: 'date',
                render: function(data, type, row, meta) {                    
                    return row.tanggal;
                }
            },
            {data: 'partisipan'},
            {data: 'notulis'},
            {data: 'action'}
        ]
    });
});
function pdf(file) {
    var win = window.open( url()+file ,'_blank');
    win.focus();
}
</script>

@endpush
    @include('core-ui.layouts._layout') 
@section('content')
<div class="row justify-content-center">
    <div class="col m-3">
        <div class="card" style="width: 100%;">

            <div class="card-header">
                Partisipan Rapat Koordinasi
            </div>

            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover responsive no-wrap" id="table" width="100%">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Judul</th>
                                <th>Tanggal</th>
                                <th>Partisipan</th>
                                <th>Notulis</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection